### ISSUE TITLE
TypeError: contact.telephony.number is not iterable

### ISSUE THREAD

**Issue by mfechner** [Rillke/fritzXML2vcard#7]
Took my some time, but the following extract from my fritzbox causes the error message:
```
				for (var number of contact.telephony.number) {
				                                     ^

TypeError: contact.telephony.number is not iterable
```

Minimal example:
```javascript
const libConvert = require('fritz-xml-2vcard');

const data = '<?xml version="1.0" encoding="UTF-8"?>\n' +
  '<phonebooks>\n' +
  '<!-- 1, id:0 , name:Telefonbuch -->\n' +
  '<phonebook owner="0" name="Telefonbuch">\n' +
  '<timestamp>1533541706</timestamp>\n' +
  '<!-- number of contacts 62 -->\n' +
  '<contact>\n' +
  '<category>0</category>\n' +
  '<person>\n' +
  '<realName>Wecker 1</realName>\n' +
  '</person>\n' +
  '<uniqueid>5</uniqueid>\n' +
  '<telephony>\n' +
  '<services>\n' +
  '</services>\n' +
  '<!-- numbers:1-->\n' +
  '<number type="" quickdial="" vanity="" prio="1" >**41</number>\n' +
  '<!-- idx:11 -->\n' +
  '<!-- ringtoneidx:nil -->\n' +
  '</telephony>\n' +
  '</contact>\n' +
  '</phonebook></phonebooks>';
const vcf = libConvert.fritzXML2vcard(data, '08131', '+49');
console.log(vcf);

```

**Comment by Rillke** [comment]
Asked for a format specification from AVM:

> Lieber AVM Support,
> 
> unter https://blog.rillke.com/fritzXML2vcard/ entsteht ein Converter,
> der FritzBox Kontakte in vCards verwandeln soll, da letztere von vielen
> Smartphones etc. gelesen werden können. Die open source Software richtet
> sich vor allem an Menschen, die nicht all ihre Kontakte in der Cloud mit
> Datensammelunternehmen teilen möchten.
> 
> Könnten Sie mir ein XML Schema oder andere vorhandene Spezifikation
> Ihres FritzBox Adressbuchs zusenden? Ggf. für verschiedene Modelle,
> falls es Abweichungen gibt?
> 
> Darf ich diese Spezifikationen mit der Software veröffentlichen?
> 
> Viele Grüße

**Comment by Rillke** [comment]
Fixed with `v3.0.2`. Thanks for this excellent report.

**Comment by mfechner** [comment]
Thanks!

**Comment by Rillke** [comment]
> vielen Dank für Ihre Anfrage an den AVM Support.

> Informationen zu FRITZ!Box-Schnittstellen und -Protokollen, die Sie für die Realisierung eigener Entwicklungs-Projekte benötigen, finden Sie auf der AVM-Internetseite.
> https://avm.de/service/schnittstellen/

**Comment by Rillke** [comment]
Auf Seite 16 von [Telefonbuch, Online-Telefonbuch, Anrufliste](https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/x_contactSCPD.pdf) leider nur ein Beispiel mit Erklärungen:

| Tag        | Type    | Description                                            |
|------------|---------|--------------------------------------------------------|
| phonebooks | Complex | Root element                                           |
| phonebook  | Complex |                                                        |
| timestamp  | Integer | Last modification                                      |
| contact    | Complex |                                                        |
| person     | Complex |                                                        |
| realName   | String  |                                                        |
| imageURL   | String  |                                                        |
| telephony  | Complex |                                                        |
| services   | Complex |                                                        |
| email      | String  | Email address                                          |
| number     | String  | Phone number                                           |
| uniqueid   | Integer | Unique ID for a single contact  (new since 2013-04-20) |

Eine Spezifikation suche ich vergeblich.
